name             'prime8base'
maintainer       'Ele Mooney'
maintainer_email 'ellenm@prime8consulting.com'
license          'All rights reserved'
description      'Installs/Configures base images for prime 8 consulting'
long_description 'Installs/Configures base images for prime 8 consulting'
version          '0.1.1'

supports 'ubuntu'
supports 'windows'

depends 'samhain'
depends 'chkrootkit'
depends 'apt'
depends 'sbp_packer'
depends 'terraform'
depends 'nodejs'
depends 'ruby_rbenv'
depends 'apt'
depends 'mongodb3'
depends 'ssh_known_hosts'
